### PR TITLE
Change dmd make target to 'auto-tester-build'

### PR DESCRIPTION
**Pull request by yebblies**

### CODE REVIEW

**Comment by yebblies** [comment]
Updated with the correct make target.

**Comment by braddr** [comment]
Thanks for updating it.  Please get at least the 'stable' and '2.067' branches updated with the changes Ideally all the ones that are setup in the auto-tester since they'll break if any builds are attempted for them.

Once the first two are done, I'll get this merged in.

**Comment by yebblies** [comment]
I've opened pull requests for all the branches listed on the autotester page:
https://github.com/D-Programming-Language/dmd/pull/4540
https://github.com/D-Programming-Language/dmd/pull/4541
https://github.com/D-Programming-Language/dmd/pull/4542
https://github.com/D-Programming-Language/dmd/pull/4543
https://github.com/D-Programming-Language/dmd/pull/4544

**Comment by yebblies** [comment]
Ok never mind about pre 2.066

**Comment by braddr** [comment]
Hrm. I really don't like that the AT isn't capable of building at least the 2.066 branch.  I'll ponder on how to restore the config file copying for that and the older branches.

I'm not going to merge this pull until monday or tuesday due to heading out of town in the morning and making changes right before disappearing is just asking for trouble, or a ruined weekend with friends.

**Comment by yebblies** [comment]
> Hrm. I really don't like that the AT isn't capable of building at least the 2.066 branch. I'll ponder on how to restore the config file copying for that and the older branches.

Or we can update the older branches to work without the config file.

> I'm not going to merge this pull until monday or tuesday due to heading out of town in the morning and making changes right before disappearing is just asking for trouble, or a ruined weekend with friends.

:( That's a shame, I'll have to find something else to do on the weekend I guess.  I'd be happy to take the blame if there are problems and they don't get fixed until next week.

**Comment by braddr** [comment]
deploying to the host 'redmond' now, well watch it for a while before deploying to others probably late tonight.

**Comment by yebblies** [comment]
Awesome, thanks!

**Comment by yebblies** [comment]
I don't think it's working, this pull request should be building ddmd as well as dmd.
https://auto-tester.puremagic.com/show-run.ghtml?projectid=1&runid=1492060&dataid=10823088&isPull=true

**Comment by braddr** [comment]
Argh.. I didn't pay attention to which repository this pull was for.  The client code has moved over to the at-client repository.  I'll apply the change there.

**Comment by yebblies** [comment]
Great, looks like it works now!  Please let me know when it's on the other hosts.

**Comment by braddr** [comment]
I'll get all of the rest of the posix hosts done some time tomorrow.  The internet in this hotel is bad enough that I might have to wait until I get home to be able to sanely work in the windows hosts.  rdp is pretty bandwidth friendly, but...

**Comment by yebblies** [comment]
Understood, whenever you can.

**Comment by braddr** [comment]
Deployed to all of the posix hosts now.  I'll finally be home in 12ish hours and will deploy to the 3 windows machines then.

**Comment by yebblies** [comment]
Thanks!

**Comment by yebblies** [comment]
Most of them have run now, no problems so far.

**Comment by braddr** [comment]
Deployed across all the hosts now.

**Comment by yebblies** [comment]
Yay! Thank you!

**Pull request merged**
