### PR TITLE
Increase vertical scale on charts

### PR DESCRIPTION
**Pull request by JinShil**
We're kicking some PR butt.  We're now off the charts!  https://auto-tester.puremagic.com/chart.ghtml?projectid=1

### CODE REVIEW

**Comment by braddr** [comment]
Of course, for that first graph off the charts is bad.  That's the number of pulls from the month that are still open.  Close some and they'll be back in-bounds.

**Comment by JinShil** [comment]
>  Of course, for that first graph off the charts is bad.

Ah right, sorry.  Anyway I modified the PR so now it only increase the scale for the issues graph.

**Comment by braddr** [comment]
Sorry, I missed that you were changing multiple graphs.  Changing the scale for the issue graph is semi-pointless.  Each release creates a giant spike as a side effect of the merge and the updates that get posted to bugzilla.  The graph would need to scale to cover (bugs fixed current week) + (bugs fixed since previous release), squashing all the other weeks fairly badly.  The current value is a compromise between hiding that there's a big spike and allowing the other weeks to show something other than a tiny sliver.

**Comment by JinShil** [comment]
So be it.

**Pull request closed without merging**
